### ISSUE TITLE
Are we breaking the link to the bones repo?

### ISSUE THREAD

**Issue by luetkemj** [VCUarts/VCUarts-bones#13]
Cause if we are there's a bunch of crap to fix like styling with ID's in _layout.scss

Why does he use those anyways?

**Comment by streeetlamp** [comment]
Yeah we probably are, its not worth it trying to keep them in sync. And I have no idea, I always think the same thing.

**Comment by streeetlamp** [comment]
Changed all of the IDs out to classes
