### ISSUE TITLE
Better Build Process

### ISSUE THREAD

**Issue by luetkemj** [VCUarts/VCUarts-bones#15]
Would be awesome to have a build process that packages the theme up completely. So we you don't have to remove node modules or git files and any of that other junk.

It would give you a clean package theme that can be uploaded to the server as is.

**Comment by streeetlamp** [comment]
totally agree, had the same thought the other day 

![68747470733a2f2f747769737465647369667465722e66696c65732e776f726470726573732e636f6d2f323031332f30332f6261746d616e2d7468756d62732d75702d7061747269636b2d682e6a7067](https://cloud.githubusercontent.com/assets/1740634/7654685/fe31d982-faec-11e4-99f2-181ffd507c86.jpg)

**Comment by luetkemj** [comment]
done
![giphy-1](https://cloud.githubusercontent.com/assets/925980/7657032/b8e70798-fafc-11e4-80f7-85a6d252e430.gif)
